- services/snapshot.go
> count only private snapshots issue#28

- public/src/app/app.component.ts
> fixed us-east-1 longitude & latitude

- README.md
> override the default aws profile

- README.md
Added note about `chmod +x` usage on OSX
n/a
Update README
n/a
> UPDATED README.md w/ note about chmod usage on OSX

- public/src/app/app.component.ts
- services/autoscaling.go
> fixed invalid memory address or nil pointer dereference

- public/src/app/app.component.html
- public/src/app/app.component.ts
- public/src/app/services/aws.service.ts
Show correct number of RDS instances
https://github.com/mlabouardy/komiser/issues/48
> show number of rds instances

- dashboard/src/index.html
> added floating prompt for product hunt

- README.md
> fix iam policy link

- dashboard/src/app/compute/gcp/gcp.component.ts
- dashboard/src/app/dashboard/aws/aws.component.ts
- dashboard/src/app/dashboard/gcp/gcp.component.ts
- dashboard/src/app/security/aws/aws.component.ts
> fix hover on map

- dashboard/src/app/compute/gcp/gcp.component.ts
- dashboard/src/app/dashboard/gcp/gcp.component.ts
> add support for europe-west6

- .circleci/config.yml
- README.md
> release v2.3.0

- dashboard/src/app/storage/ovh/ovh.component.ts
> fix angular aot build

- Godeps/Godeps.json
- vendor/github.com/ovh/go-ovh/LICENSE
- vendor/github.com/ovh/go-ovh/ovh/configuration.go
- vendor/github.com/ovh/go-ovh/ovh/consumer_key.go
- vendor/github.com/ovh/go-ovh/ovh/error.go
- vendor/github.com/ovh/go-ovh/ovh/logger.go
- vendor/github.com/ovh/go-ovh/ovh/ovh.go
- vendor/gopkg.in/ini.v1/.gitignore
- vendor/gopkg.in/ini.v1/.travis.yml
- vendor/gopkg.in/ini.v1/LICENSE
- vendor/gopkg.in/ini.v1/Makefile
- vendor/gopkg.in/ini.v1/README.md
- vendor/gopkg.in/ini.v1/error.go
- vendor/gopkg.in/ini.v1/file.go
- vendor/gopkg.in/ini.v1/ini.go
- vendor/gopkg.in/ini.v1/key.go
- vendor/gopkg.in/ini.v1/parser.go
- vendor/gopkg.in/ini.v1/section.go
- vendor/gopkg.in/ini.v1/struct.go
> added ovh client

- Dockerfile
> build v2.3.0 docker image

- deployment/README.md
- deployment/alb-ingress.yaml
- deployment/deployment.yaml
- deployment/service.yaml
Added under `./deployment` folder files for running komiser in kubernetes
> Added kubernetes deployment and README for it

- README.md
Updating the brew tap command in accordance with bug #212
> update brew tap command

- README.md
PR relating to internal Oraculi ticket tracked on Linear com-56 to overhaul the current Komiser readme.md file
COM-56
Updating the header image
Adding link to Komiser docs instead of adding code to readme file
Updated links
Restructured content layout
Added Table of contents
> large number of updates and changes to readme file

- README.md
Added new readme image.
Changed legacy Oraculi links
> update tw assests and links

- handlers/resources_handler.go
- handlers/stats_handler.go
> chore: remove logs

- providers/aws/aws.go
> chore: show list of whitelisted regions in logs

- handlers/resources_handler.go
- handlers/stats_handler.go
- internal/api/v1/endpoints.go
- internal/internal.go
> added JSON array support in SQLite

- go.mod
- go.sum
- internal/internal.go
> feat: fetch resources very 1 hour

- go.mod
- go.sum
- internal/config/load.go
- internal/internal.go
- models/config.go
- providers/civo/civo.go
- providers/civo/compute/instances.go
- providers/civo/kubernetes/clusters.go
- providers/civo/network/firewalls.go
- providers/civo/network/networks.go
- providers/civo/storage/volumes.go
- providers/providers.go
Added support of the following services:
- Kubernetes
- Compute instances
- Volume
- Firewalls
- Networks
> CIVO provider support

- providers/civo/compute/instances.go
- providers/civo/kubernetes/clusters.go
Thanks to @saiyam1814 we've tweaked the cost formula for compute instances and added k8s costs
https://github.com/tailwarden/komiser/issues/275
> Estimate CIVO K8s cost

- go.mod
- go.sum
- providers/aws/apigateway/apis.go
- providers/aws/aws.go
Collect AWS API Gateway resources
> feat: support aws api gateways #250

- providers/digitalocean/digitalocean.go
- providers/k8s/k8s.go
- providers/oci/oci.go
> fix package names for providers

- providers/digitalocean/droplets/droplets.go
Add DigitalOcean droplets cost calculation.
> Add DigitalOcean droplets cost

- providers/digitalocean/digitalocean.go
- providers/digitalocean/network/firewalls.go
Add firewalls resource to digitalocean provider.
> add firewalls resource to digitalocean provider

- providers/digitalocean/digitalocean.go
- providers/digitalocean/network/vpcs.go
Add DigitalOcean VPC resource.
> Add DigitalOcean VPC resource

- providers/digitalocean/digitalocean.go
- providers/digitalocean/network/loadbalancers.go
Add DigitalOcean Load Balancer resource.
Related [issue](https://github.com/tailwarden/komiser/issues/254).
> Add DigitalOcean Load Balancer resource

- providers/aws/lambda/functions.go
Addressing bug found in ticket tech-756.
> add nil pointer check for metricsInvocationsOutput

- policy.json
Permissions added:
- ecr:DescribeRepositories
- elasticfilesystem:DescribeFileSystems
- rds:DescribeDBClusters
> added describe permission to EFS, RDS clusters, ECR repos

- README.md
Added a flag to two readme images to force a CDN cache refresh.
> add flag to images to refresh cache

- handlers/views_handler.go
- internal/api/v1/endpoints.go
Exposed endpoint to exclude hidden resources from custom views listing
> exclude hidden resources

- go.mod
- go.sum
- providers/aws/aws.go
- providers/aws/elasticache/clusters.go
Add AWS ElastiCache
https://github.com/tailwarden/komiser/issues/249
> feat: support ElastiCache clusters

- providers/linode/linode.go
- providers/linode/storage/databases.go
- providers/linode/storage/volumes.go
Collect Linode volumes and databases resources
> Collect Linode storage resources

- policy.json
Permissions added:
`elasticache:ListTagsForResource`
> added list tags permission to ElastiCache

- dashboard/README.md
- Made a minor update to the sequence of commands to run a dev version of the dashboard
> update dashboard readme file

- providers/k8s/core/deployments.go
- providers/k8s/k8s.go
Signed-off-by: Anurag <contact.anurag7@gmail.com>
- This PR adds support for deployments 
Fixes #321
Added support for deployments
<details>
<summary> Dashboard Screenshot </summary>
</details>
> add support for k8s deployments

- README.md
- Updated README links that pointed to pages that will be broken once this [PR](https://github.com/tailwarden/docs.komiser.io/pull/39) is merged.
- Added some UTM parameters that were missing.
> Com 314/updpate-readme-links

- providers/civo/civo.go
- providers/civo/storage/objectstores.go
Collect Civo [object stores](https://www.civo.com/api/object-stores)
> feat: support civo object store #319

- providers/civo/civo.go
- providers/civo/network/loadbalancers.go
Collect Civo [load balancers](https://www.civo.com/load-balancers)
> added Civo load balancers

- providers/aws/aws.go
- providers/aws/cloudwatch/alarms.go
Add Support for AWS CloudWatch Alarms
[#234 ](url)
Tested locally. Working absolutely fine. You can see in the image.
> feat: support aws cloudwatch alarms #234

- providers/k8s/core/ingress.go
- providers/k8s/core/pv.go
- providers/k8s/core/pvc.go
- providers/k8s/core/sa.go
- providers/k8s/k8s.go
Signed-off-by: Anurag <contact.anurag7@gmail.com>
- support for serviceaccount, pv, pvc and ingress
Fixes #320 #322 #323 #324
> add support for other kubernetes resources

- CONTRIBUTING.md
- README.md
- providers/aws/apigateway/apis.go
- Added Linode to Readme
- Added Tencent to Readme
- Removed reference to OVH from Readme.
> Com 323/update readme to include new providers

- go.mod
- go.sum
- policy.json
- providers/aws/cloudfront/distributions.go
- providers/aws/dynamodb/tables.go
- providers/aws/ecr/repositories.go
- providers/aws/efs/efs.go
- providers/aws/eks/clusters.go
- providers/aws/elb/loadbalancers.go
- providers/aws/sns/topics.go
Support of the following services:
- EKS
- DynamoDB
- EFS
- CloudFront
- SNS
- ELB
Also, refactoring the recommended AWS IAM policy by using wildecards
> Added cost to remaining AWS resources

- providers/aws/eks/clusters.go
> fix: eks nil pointer

- dashboard/components/inventory/components/InventoryLayout.tsx
- dashboard/components/inventory/hooks/useInventory/helpers/getCustomViewInventoryListAndStats.ts
- dashboard/components/inventory/hooks/useInventory/helpers/infiniteScrollSearchedCustomViewList.ts
- dashboard/components/inventory/hooks/useInventory/useInventory.tsx
> fix: change id to view on url params

- PULL_REQUEST_TEMPLATE.md
This pull request proposes to add a new template for pull requests to the repository. The new template provides a clear and concise format for contributors to follow when submitting changes to the codebase. The template includes sections for describing the problem, solution, changes made, instructions for testing, relevant screenshots, notes, and a checklist.
The goal of this pull request is to ensure that all pull requests have a consistent format and provide enough information for reviewers to easily understand the changes and assess their impact on the codebase. This will help streamline the review process, reduce the time spent on reviewing, and increase the overall efficiency of the development workflow.
The new template has been designed to be flexible and can be customized to suit …
> New PR Template

- providers/linode/linode.go
- providers/linode/networking/firewalls.go
- providers/linode/networking/node_balancers.go
Collect NodeBalancers and Firewalls in Linode
https://github.com/tailwarden/komiser/issues/329 and https://github.com/tailwarden/komiser/issues/327
> Feat: Collect nodebalancers and firewalls in linode

- providers/oci/developerservices/applications.go
- providers/oci/developerservices/functions.go
- providers/oci/iam/policies.go
- providers/oci/oci.go
- providers/oci/oracledatabase/autonomousdatabase.go
- providers/oci/storage/blockvolumes.go
- providers/oci/storage/buckets.go
Collect resources[BlockVolumes, Functions, Applications, Buckets, Policies, Autonomous Databases] in OCI
https://github.com/tailwarden/komiser/issues/245,
https://github.com/tailwarden/komiser/issues/244,
https://github.com/tailwarden/komiser/issues/243
https://github.com/tailwarden/komiser/issues/242
https://github.com/tailwarden/komiser/issues/238
> Feat:  Collect resources[BlockVolumes, Functions, Applications, Buckets, Policies, Autonomous Databases] in oci

- go.mod
- go.sum
- providers/digitalocean/databases/databases.go
- providers/digitalocean/digitalocean.go
- providers/digitalocean/functions/namespaces.go
- providers/digitalocean/functions/triggers.go
- providers/digitalocean/k8s/kubernetes.go
- providers/digitalocean/kubernetes/kubernetes.go
- providers/digitalocean/storage/volumes.go
https://github.com/tailwarden/komiser/issues/257
https://github.com/tailwarden/komiser/issues/255
https://github.com/tailwarden/komiser/issues/252
https://github.com/tailwarden/komiser/issues/237
- Updated godo package to latest (changes in go.mod)
- Added collector for DO k8s
- Added collector for DO volumes
- Added collector for DO mongoDb
- Added collector for DO functions
- Create account on digital ocean and get the api token and update it in config.toml
- Pull the changes and run `go build`.
- Run `./komiser start --port 3000`
@mlabouardy
> Feat add resources to digital ocean

- README.md
- Added Gif to README
- Added links to Azure and Scaleway documentation
- Included new cloud providers in the introduction text
> update readme to include ref to scaleway and azure + gif

- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorerChart.tsx
> fix: cost explorer fetch

- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorerChart.tsx
- providers/azure/azure.go
- providers/azure/networking/load_balancers.go
Support Azure Load Balancers
#395
> Support Azure Load Balancers #395

- .github/go.yml
Added go linters in github workflows
> Added Linters

- go.mod
- go.sum
- providers/azure/azure.go
- providers/azure/databases/sql.go
Requested in issue #388 this PR adds support for getting "SQL Server" resources from Azure.
> Azure SQL server support

- .gitignore
- dashboard/components/toast/Toast.stories.tsx
- dashboard/components/toast/Toast.tsx
In an effort to document Komiser components, this PR adds the `Toast` component to our storybook. Related issue #419 
cc @victorgaard
> Add Toast component to storybook

- providers/aws/ec2/volumes.go
This PR adds a (very rough) cost estimation for AWS EBS Volumes. The only thing taken into consideration is the type of the volume (`standard, gp2, gp3, ...`) etc.
This PR closes #414
> Add cost estimation for EBS volumes

- .circleci/config.yml
- dashboard/components/banner/Banner.tsx
- dashboard/components/card/Card.tsx
- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorerChart.tsx
- dashboard/components/dashboard/components/resources-manager/hooks/useResourcesManagerChart.tsx
- dashboard/components/inventory/components/InventorySidePanel.tsx
- dashboard/components/inventory/components/InventoryStatsCards.tsx
- dashboard/components/inventory/components/InventoryTable.tsx
- dashboard/components/inventory/components/InventoryTableBulkActions.tsx
- dashboard/components/inventory/components/view/InventoryView.tsx
- dashboard/components/inventory/components/view/alerts/InventoryViewAlertsDisplay.tsx
- dashboard/components/inventory/hooks/useInventory/types/useInventoryTypes.ts
We want to make sure that every PR is verified, meaning all tests pass and linting rules are obeyed. This PR enables running the CI/CD pipeline on every branch, thus on every PR. 
The master branch is being ignored for the testing/linting, because the build and deploy job already does that.
> Enable test run on CI/CD for frontend

- dashboard/.husky/pre-commit
- dashboard/components/layout/Layout.tsx
- dashboard/components/layout/hooks/useTelemetry.tsx
- dashboard/environments/environment-production.ts
- dashboard/environments/environment-sandbox.ts
- dashboard/environments/environment-staging.ts
- dashboard/environments/environment.ts
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/services/settingsService.ts
- dashboard/utils/providerHelper.ts
- Added Sentry to collect frontend errors if telemetry is enabled and env is production
- Added `npm test` to pre-commit hook
> Add Sentry to collect frontend errors

- go.mod
- go.sum
- internal/config/load.go
- internal/internal.go
- models/config.go
- providers/mongodbatlas/mongodbatlas.go
- providers/providers.go
This PR adds the boilerplate for fetching [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) resources. The actual resources fetching will be done in a separate PR, to follow.
> Boilerplate for MongoDB Atlas Provider

- dashboard/.eslintrc.json
- dashboard/components/card/Card.test.tsx
- dashboard/components/card/Card.tsx
- dashboard/components/card/__tests__/Card.test.tsx
- dashboard/components/tooltip/Tooltip.tsx
- dashboard/jest.config.js
- dashboard/jest.setup.js
- dashboard/package-lock.json
- dashboard/package.json
- Added tests for our Card component
- Test covers:
- If card is rendered without crashing
- If card renders the icon
- If card renders the value in the correct format
- If card renders the value in the correct format (currency)
- If card display the tooltip if tooltip is passed as props
- `npm run test:watch` from `dashboard` folder
- press `p`
- enter `card` as pattern
- `Card test`
> Add unit tests to Card

- dashboard/README.md
- Updated dashboard README file to include more details about Komiser Dashboard, components, testing and overall conventions.
> Dashboard README update

- dashboard/components/inventory/components/InventoryViewsHeader.tsx
- dashboard/components/inventory/components/view/InventoryView.tsx
- dashboard/components/modal/Modal.tsx
- Fix the modal style on Firefox, which was not showing the modal properly.
> Fix modal styling on Firefox

- providers/aws/aws.go
- providers/aws/iam/groups.go
- Added support for AWS IAM Groups
AWS IAM Groups have no tags and no billing.
@mlabouardy
> Added support for AWS IAM Groups

- policy.json
- providers/aws/kms/keys.go
This PR addresses #614 
AWS managed keys are free, and every other key costs 1$/month.
> feat: aws managed keys are free

- README.md
> Update README.me, mostly on links pointing to docs

- README.md
> Cyril all patch docs

- go.mod
- go.sum
> chore: run go mod tidy

- dashboard/components/layout/Layout.tsx
Closes #699
Update link to https://docs.komiser.io/docs/introduction/getting-started#self-hosted
@mlabouardy
> fix: url for connect account button

- go.mod
- go.sum
- providers/gcp/certificate/certificate.go
- providers/gcp/gcp.go
Add Support for Certificates in GCP in Komiser
Closes #668 
```
[[gcp]]
name="demo"
serviceAccountKeyPath="/path/to/serviceAccount/secret.json"
```
> feat: support certificates in GCP

- providers/gcp/gcp.go
- providers/gcp/iam/serviceAccount.go
> Add Support for IAM Service Accounts in GCP

- go.mod
- go.sum
- providers/gcp/gcp.go
- providers/gcp/kms/keys.go
Added support for GCP KMS keys
> Tech 1062/support keys gcp

- go.mod
- go.sum
- providers/aws/aws.go
- providers/aws/cloudwatch/log_metrics.go
Closes #464 
We need to update the documented policy and enable **CloudwatchFullAccess** policy in user IAM to avoid any warnings.
> Add Support for AWS CloudWatch Metric Streams

- go.mod
- go.sum
- providers/aws/aws.go
- providers/aws/servicecatalog/applications.go
Closes #577 
Need to enable [AWSServiceCatalogAdminFullAccess](https://us-east-1.console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess) in the policy in docs!
> Add Support for AWS Service Catalog Products

- .gitignore
Update the template.go to include latest frontend code
> chore: update template to be latest dashboard code

- providers/aws/aws.go
- providers/aws/ec2/keypair.go
> Add Support for AWS EC2 Key Pair

- go.mod
- go.sum
- providers/aws/aws.go
- providers/aws/systemsmanager/maintenance_window.go
Closes #583 
- Need to add the following policy to the user: `AmazonSSMFullAccess`
> Add Support for AWS Systems Manager Maintenance Window

- providers/aws/aws.go
- providers/aws/ec2/placement_groups.go
> Add Support for AWS EC2 Placement Group

- dashboard/pages/_app.tsx
> feat: show hiring message in browser console

- dashboard/components/layout/Layout.tsx
- dashboard/components/navbar/Navbar.tsx
- dashboard/pages/inventory.tsx
> chore: fixed links

- dashboard/components/dashboard/components/resources-manager/hooks/useResourcesManagerChart.tsx
> fix: resources display when over 1k

- utils/regions.go
> Fix AWS sao paulo region lat/long

- cmd/version.go
the komiser version gave a simple text for the instead of logo
used ascii art to generate a logo for it
- #834
```bash
go run -v . version
```
> enhancement: add new ascii art logo

- providers/aws/aws.go
- providers/aws/rds/cluster_snapshot.go
fixes #563 
Adding support to collect Amazon RDS Cluster Snapshots.
- added `cluster_snapshot.go` file in the `rds` folder.
- want to find the correct format for `Link` in the `Resources` slice.
@mlabouardy
> RDS Cluster Snapshot  feature

- providers/aws/cloudwatch/dashboards.go
Missing cost calculation for AWS Cloudwatch Dashboards
- Upto 3 dashboards are in the free tier
- Every dashboard after which is 3$ per month flat
- 4 Dashboards:
- 3 Dashboards:
> Cost Calculation: AWS CloudWatch Dashboards

- handlers/resources_handler.go
- models/resource.go
Addresses the issue of nonfunctional search in #813 
Have kept the original queries commented for you to refer, please remove when not needed!
> Fix Search Querying

- providers/aws/aws.go
- providers/aws/ecs/containers.go
Please review my PR @ChristianWitts
> Adding ECS Container Services

- providers/linode/linode.go
- providers/linode/postgres/instances.go
#821 
Added file Collect Linode Postgres Instances
@ShubhamPalriwala
> Support Linode Postgres Instances

- dashboard/package.json
Preparing Release: Bump Package version to v3.1.0
> Bump release version to v3.1.0

- dashboard/components/inventory/components/InventoryActiveFilters.tsx
- dashboard/components/inventory/components/filter/InventoryFilterSummary.tsx
The design implementation of fllter tags , buttons and dropdown is not aligned with figma design 
Have modified design of components to match with figma design
- fixed width of filter preview inside the adding filter container
- fixed font weight and overall spacing in filter tags
- modified clear filter button as per figma design
- added hover effect to add button and clear filter
https://github.com/tailwarden/komiser/assets/29349136/2ac76510-f1c9-41f4-ac3b-e8f0161c992c
@mlabouardy
> fix(filter-tags): fix tags and button design

- policy.json
access denied error due to missing IAM access for s3, cloudwatch and ssm
Update policy.json to provide access to s3, cloudwatch and ssm list access
policy.json …
> Update policy.json to provide access to s3, cloudwatch and ssm list access

- docs/mint.json
> removed the api tab since it was just a placeholder

- docs/getting-started/installation.mdx
Updated the link pointing to a newly updated Komiser installation video.
> added an updated Komiser installation video

- .github/dependabot.yml
It would be nice to have lable and reviewers in dependabot
> dependabot: lable and reviewers

- docs/community-support/contributing.mdx
- docs/community-support/events.mdx
- docs/community-support/faqs.mdx
- docs/configuration/cloud-providers/aws.mdx
- docs/configuration/cloud-providers/civo.mdx
- docs/configuration/cloud-providers/k8s.mdx
- docs/getting-started/installation.mdx
- docs/getting-started/introduction.mdx
- docs/getting-started/quickstart.mdx
- docs/guides/dashboard.mdx
- docs/mint.json
- Add styling changes as per #953 (@AllieMendes the only thing is that I wasn't able to add the gradient to the icons, it doesn't seem to be possible) 
- Added the Google Analytics tracker in mint.json
- Removed the large amount of bullet points from the introduction page.
> added rounded images and videos also added GA tracker

- .github/workflows/build_test_pr.yml
- go.mod
chore: upgrade go version in go mod
> chore: upgrade go version in go mod

- .gitignore
> fix: paths ignored by `.gitignore`

- migrations/20230619100000_add_new_relation_field.go
- models/relation.go
- providers/aws/ec2/autoscaling_groups.go
- providers/aws/ec2/instances.go
- providers/aws/ec2/volumes.go
- providers/aws/ec2/vpcs.go
- providers/aws/iam/roles.go
- providers/aws/lambda/functions.go
Collected the following AWS connections:
> Collect additional AWS services connections

- handlers/resources_handler.go
- internal/api/v1/endpoints.go
> Support graph filters

- docs/getting-started/quickstart.mdx
- just a tiny typo fixed!
@mlabouardy
> docs: a tiny fix quickstart.mdx

- dashboard/package-lock.json
- dashboard/package.json
see the changelog-https://github.com/vercel/next.js/releases/tag/v13.5.6
> Upgrade next 13.5.6

- dashboard/components/navbar/Navbar.tsx
Update the link to redirect users to this new page (https://www.tailwarden.com/changelog/komiser)
Update the link to redirect users to this new page (https://www.tailwarden.com/changelog/komiser)
- Updated the link to redirect users to this new page (https://www.tailwarden.com/changelog/komiser)
@AllieMendes 
closes #1164
> fix: update_redirect_to_changelog_link

- dashboard/components/explorer/hooks/useDependencyGraph.tsx
- handlers/resources_handler.go
- models/relation.go
> fix: civo dep graph nodes

- internal/internal.go
- providers/ovh/ovh.go
#1205 
Submitting the tasks to worker pool instead of executing synchronously.
- Updated respective function signatures
- Used `providers.WorkerPool.SubmitTask` to submit the task to worker pool
> fix: Resource fetching performance improvement for OVH

- internal/internal.go
- providers/civo/civo.go
- providers/digitalocean/digitalocean.go
- providers/k8s/k8s.go
- providers/linode/linode.go
- providers/oci/oci.go
- providers/tencent/tencent.go
#1198 #1199 #1200 #1201 #1202 #1203
Submitting the tasks to worker pool instead of executing synchronously.
- Updated respective function signatures
- Used `providers.WorkerPool.SubmitTask` to submit the task to worker pool
> [KOM-38]: Resource fetching performance improvement for CIVO, DigitalOcean, OCI, Linode, K8s, Tencent

- providers/aws/aws.go
- providers/azure/azure.go
- providers/civo/civo.go
- providers/digitalocean/digitalocean.go
- providers/gcp/gcp.go
- providers/k8s/k8s.go
- providers/linode/linode.go
- providers/mongodbatlas/mongodbatlas.go
- providers/oci/oci.go
- providers/ovh/ovh.go
- providers/providers.go
- providers/scaleway/scaleway.go
- providers/tencent/tencent.go
https://go.dev/blog/loopvar-preview
Make a copy of the loop var for passing on.
- Fixed accidental loop capture for all providers
- A couple chores
> Fix accidental loop capture

- dashboard/components/inventory/components/view/alerts/InventoryViewAlertsChooseAlertMethod.tsx
This pull closes #1259 
@AllieMendes
> fix: wrong slack guide url

- .github/workflows/build_test_pr.yml
- .github/workflows/hacktoberfest-comment.yml
- .github/workflows/release.yml
Build and Test kimiser with node v20
> Upgrade: Build and Test komiser with node v20

- dashboard/styles/globals.css
see in CI-https://github.com/tailwarden/komiser/actions/runs/7363465848/job/20044503001#step:7:26
Replace @variants with @layer 
> @variants directive has been deprecated

- internal/internal.go
No problem just a typo
just a typo ;)
functoin name
it still build, so its bueno ;)
do I need to?
💯 
> Fix typo in triggerFetchingWorkflow function

- docker/docker-compose.postgres.yml
Setup postgresSQL16 docker image instead 13
> Setup postgresSQL16 docker image

- .github/dependabot.yml
Set timezone and  limit for dependabot PR
> Set timezone and  limit for dependabot PR

- .github/workflows/lint.yml
> Deprecated github action

- .github/dependabot.yml
- .github/workflows/lint.yml
- CONTRIBUTING.md
- dashboard/components/inventory/components/InventoryStatsCards.tsx
- dashboard/components/inventory/components/InventoryTable.tsx
- dashboard/components/inventory/hooks/useInventory/useInventory.tsx
- dashboard/components/tooltip/Tooltip.tsx
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/pages/inventory.tsx
- dashboard/styles/globals.css
- dashboard/utils/serviceHelper.ts
- docker/docker-compose.postgres.yml
- handlers/accounts_handler.go
- handlers/dashboard_handler.go
- internal/internal.go
- policy.json
- providers/aws/aws.go
- providers/aws/systemsmanager/managedinstances.go
- providers/aws/utils/utils.go
**Changelog**
- Fixed onboarding wizard
- Opencost support in onboarding wizard
- Support for SSM based instances
- Shortcut to Tailwarden in inventory table
- Added 6 months AWS cost history
> v3.1.9 release 🚀

- dashboard/package-lock.json
- dashboard/package.json
see- https://github.com/vercel/next.js/releases/tag/v14.1.0
> Update to Next.js 14.1.0

- dashboard/components/cloud-account/components/CloudAccountsLayout.tsx
Rename Add an Account button name to Connect account
fixes" #1343
> Button: Add an Account to Connect account

- dashboard/package-lock.json
- dashboard/package.json
- handlers/helper.go
**Changelog**
- onboarding fails to populate config file bug fix
- AWS CDK for helm chart deployment on EKS
> v3.1.14 release 🚀

- cmd/config.go
- cmd/start.go
- dashboard/package-lock.json
- dashboard/package.json
- handlers/helper.go
- internal/config/create.go
- internal/config/load.go
** Changelog **
- Failing onboarding wizard for IAM role fix
- Config create util separation
> v3.1.15 release 🚀

- repository/postgres/postgres.go
- repository/sqlite/sqlite.go
count doesn't exist on the struct `totalOutput`
> fix: TotalOutput does not have column count

- controller/accounts.go
- controller/alerts.go
- controller/controller.go
- controller/views.go
- handlers/dashboard_handler.go
- repository/core.go
- repository/postgres/postgres.go
- repository/sqlite/sqlite.go
`LastInsertedId` is not supported by postgres
Workaround for `LastInsertedId`
> fix: unsupported operations by driver

- .github/workflows/release.yml
- handlers/dashboard_handler.go
version update.
Will update to latest goreleaser in a future release
> goreleaser hotfix

- providers/aws/redshift/cluster.go
- providers/aws/redshift/eventsubscription.go
Added support for Redshift clusters
> Add support for Redshift clusters
