- README.md
The documentation incorrectly lists the tap `org|user` to be `mlabouardy` and not the correct root of `komiserio`.
Fixes #92 
Signed-off-by: Christian Witts <cwitts@gmail.com>
> brew tap location fix

- README.md
Currently the bucket @ https://komiser.s3.amazonaws.com is unavailable. This creates confusion for new people pulling the policy down. I would suggest just pointing it to the policy in the master branch.
Non
Change the wget for the AWS policy to point directly to the github static file.
> Aws Policy Location Update

- .github/workflows/hello-to-new-contributors.yml
In order to avoid all triggerable actions for Issues and Pull requests, we specified to trigger only on the `opened` action.
> restricted triggers to just issues and PRs opened

- .github/workflows/hello-to-new-contributors.yml
We still had some legacy Oraculi links and intances that had to be changed to Tailwarden.
> remove any instance Oraculi from the github-action workflow

- providers/aws/rds/clusters.go
A Discord member (mlaccetti) brought to our attention that there was no nil pointer check on for RDS cluster DatabaseName and it returned a panic error if the cluster had no name, this nil pointer check should avoid this error.
> add check for DatabasName nil pointer in RDS clusters file

- handlers/resources_handler.go
- handlers/stats_handler.go
The actual endpoints now support the cost field. The supported operators are:
```
BETWEEN
EQUAL
GREATER_THAN
LESS_THAN
```
https://github.com/tailwarden/komiser/issues/274
> feat: added cost filter to filters set

- dashboard/.eslintrc.json
- dashboard/components/input/Input.tsx
- dashboard/components/inventory/components/InventoryViewsTabs.tsx
- dashboard/components/inventory/components/filter/InventoryFilter.tsx
- dashboard/components/inventory/components/filter/InventoryFilterFieldOptions.tsx
- dashboard/components/inventory/components/filter/InventoryFilterOperator.tsx
- dashboard/components/inventory/components/filter/InventoryFilterSummary.tsx
- dashboard/components/inventory/components/filter/InventoryFilterValue.tsx
- dashboard/components/inventory/components/filter/hooks/useFilterWizard.tsx
- dashboard/components/inventory/components/view/InventoryView.tsx
- dashboard/components/inventory/components/view/hooks/useViews.tsx
- dashboard/components/inventory/hooks/useInventory.tsx
- dashboard/utils/regex.tsx
- Added support to filtering resources by cost using the operators: equal, between, greater than & less than.
- Changed URL params for views to display view id and no longer view name (now supports the same name for multiple views).
- Minor fixes.
- #274
> Filter resources by cost + minor improvements

- cmd/start.go
- internal/internal.go
For running the Komiser without docker maybe useful run it on localhost or any preferable address for security reasons.
With this changes you can run the Komiser with CLI flag `--listen-address 127.0.0.1` (or `-a 127.0.0.1` short flag).
The default address is `0.0.0.0` for backwards compatibility.
> add listen-address CLI flag

- providers/aws/efs/efs.go
- providers/aws/s3/buckets.go
I added a couple of lines to check if the pointer (metricsBucketSizebytesOutput) is not nil, if the length of the slice is greater than zero and then check if there is an error.
> added nil pointer check to buckets.go

- Makefile
- Add `help` target to Makefile:
```
➜ make help
komiser v3.0.0
Available targets:
build     Build for the current platform.
package   Build for all supported platforms.
test      Run tests.
version   Show version.
clean     Remove previous builds and clear test cache.
help      Show this message.
```
- Make `VERSION` variable overridable from env:
```
➜ make version
version: nemca/add-help-to-makefile
commit: 0039bbc
➜ VERSION=v3.0.0 make version
version: v3.0.0
commit: 0039bbc
```
> add help to makefile

- handlers/resources_handler.go
- handlers/views_handler.go
- internal/api/v1/endpoints.go
Allow user to hide or unhide resources from a custom view. This can be useful to hide shared resources (K8s clusters, Databases, etc) from team/application views
> feat: hide/unhide resources from view

- .circleci/config.yml
- Dockerfile
- cmd/start.go
- go.mod
- go.sum
- internal/api/v1/endpoints.go
- internal/internal.go
We collect telemetry data for only two reasons: so that we can improve our product, and so that we can continue working on this project full-time.
In order to create a better product, we need reliable quantitative information. The data we collect helps us fix bugs, evaluate the success of features, and better understand our users' needs.
We also need to prove that people are actually using Komiser. Usage metrics help us justify our existence to investors so that we can keep this project alive
By default, the Komiser CLI collects some anonymous usage data. There are two types of data we collect: errors and stats. We use Sentry to collect errors and performance issues. While Segment is used to track product usage.
PS: Komiser will not collect any cloud provider information or credentials :) …
> Enable segment and sentry

- handlers/dashboard_handler.go
- internal/api/v1/endpoints.go
Exposed an endpoint with the following stats:
- Number of connected cloud accounts
- Number of active regions
- Up-to-date monthly cost
- Number of cloud resources
> feat: expose dashboard stats

- dashboard/components/dashboard/components/cloud-map/hooks/useCloudMap.tsx
- dashboard/components/dashboard/components/cost-explorer/DashboardCostExplorer.tsx
- dashboard/components/dashboard/components/cost-explorer/DashboardCostExplorerCard.tsx
- dashboard/components/dashboard/components/cost-explorer/DashboardCostExplorerError.tsx
- dashboard/components/dashboard/components/cost-explorer/DashboardCostExplorerSkeleton.tsx
- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorer.tsx
- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorerChart.tsx
- dashboard/components/dashboard/components/cost-explorer/utils/dateHelper.ts
- dashboard/components/dashboard/components/cost-explorer/utils/mockDataChart.ts
- dashboard/components/dashboard/components/resources-manager/DashboardResourcesManager.tsx
- dashboard/components/dashboard/components/resources-manager/DashboardResourcesManagerCard.tsx
- dashboard/components/dashboard/components/resources-manager/DashboardResourcesManagerError.tsx
- dashboard/components/dashboard/components/resources-manager/hooks/useResourcesManager.tsx
- dashboard/components/dashboard/components/resources-manager/hooks/useResourcesManagerChart.tsx
- dashboard/components/dashboard/components/top-stats/DashboardTopStatsCards.tsx
- dashboard/components/dashboard/utils/mockDataForDashboard.ts
- dashboard/components/layout/Layout.tsx
- dashboard/components/layout/hooks/useGlobalStats.tsx
- dashboard/pages/dashboard.tsx
- dashboard/services/settingsService.ts
- Added cost explorer widget to the dashboard (will remain hidden until next release)
- Plugged the API for Cloud map widget & Resources manager widget
`Cost explorer loading`
`Cost explorer error`
`Cost explorer success`
> Cost explorer widget + API plugged for Cloud Map & Resources Manager

- dashboard/components/dashboard/components/cloud-map/DashboardCloudMapCard.tsx
- dashboard/components/dashboard/components/cloud-map/hooks/useCloudMapExpand.tsx
- dashboard/components/inventory/components/InventoryLayout.tsx
- dashboard/components/navbar/Navbar.tsx
- dashboard/tailwind.config.js
- `Navbar`: added a link to the Komiser logo in the navbar pointing to `/dashboard`
- `Inventory`:  when `All Resources` is clicked from the sidebar, the page will reload and existing filters will be reset.
- `Dashboard`:  added an expand button to the cloud map widget. When clicked, the cloud map will take 100% of the screen width and height.
`Expand cloud map`
> Komiser minor improvements

- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorerChart.tsx
- Hot fix to prevent `getDatasets` (cost explorer widget) from running if the data is empty.
> fix: cost explorer fetch

- providers/aws/apigateway/apis.go
- providers/aws/cloudfront/distributions.go
- providers/aws/dynamodb/tables.go
- providers/aws/ec2/instances.go
- providers/aws/eks/clusters.go
- providers/aws/elb/loadbalancers.go
- providers/aws/lambda/functions.go
- providers/aws/s3/buckets.go
- providers/aws/sns/topics.go
- providers/aws/sqs/queues.go
- utils/datecalc.go
In order to estimate the cost of some AWS resources, we utilize the custom made method `BeginningOfMonth`. This method took into account the timestamp when the resources were fetched, thus provided incorrect cost estimations.
Refactored the method in order to provide only the date in `YYYY-MM-DD` format.
- Refactored `BeginningOfMonth` method.
- Moved it to `utils` directory and imported it as a package where needed instead of declaring it every time.
In case of an error in the process of getting the date, the method returns the `time.NOW()` so the cost is estimated as `0`.
@mlabouardy
> Fix/8 incorrect aws cost estimations due to BeginningOfMonth method

- handlers/resources_handler.go
- handlers/telemetry_handler.go
- internal/api/v1/endpoints.go
This PR adds a very simple `GET /telementry` endpoint, which returns a json response with
```
{
telemetry_enabled: true|false
}
```
that serves as the basis for collecting analytics in the frontend.
> Add /telemetry endpoint

- go.mod
- go.sum
- internal/internal.go
- models/config.go
- models/stat.go
Currently, developers can set up alerts to track the cost and usage of their infrastructure. However, those alerts are triggered when certain events happen (exceeding the monthly budget, or a sudden increase in the number of resources). It would useful to have weekly reporting as it provides a more consolidated view of the data, allowing for easier trend analysis and identification of issues that require attention.
Sending a weekly reporting on Slack each Friday at 9am (UTC) with the following metrics:
- Tags coverage: how many resources are untagged and list of most used tags
- Cost breakdown grouped by provider, region, account, and service
- I used the current Slack integration to send the weekly reporting. I couldn't attach charts to the notifications as we currently use Slack …
> Send weekly reporting (tags coverage and cost breakdown) on Friday

- providers/mongodbatlas/clusters/clusters.go
- providers/mongodbatlas/mongodbatlas.go
This PR adds a rough estimation for MongoDB Atlas clusters. The estimation is based on https://www.mongodb.com/pricing for dedicated clusters only.
> Add cost estimation for MongoDB clusters

- providers/mongodbatlas/clusters/clusters.go
- providers/mongodbatlas/clusters/clusters_test.go
- utils/regions.go
The MongoDB Atlas clusters provide region names in a different format than their underlying cloud represents them. E.g. for the AWS region `eu-central-1`, MongoDB Atlas API returns `EU_CENTRAL_1`. This prohibits the resources being shown in the cloud map, which this PR fixes.
> Add normalization for region names of MongoDB clusters

- handlers/csv_handler.go
- internal/api/v1/endpoints.go
- models/resource.go
This PR adds a new route `GET /resources/export-csv` which exports all resources in the DB as a .csv and downloads the file in the Browser. To download the CSV for a custom view the endpoint is `GET /resources/export-csv/{viewId}`.
> Add csv export endpoint for resources

- .circleci/config.yml
- .github/workflows/build_test.yml
- .github/workflows/build_test_pr.yml
This PR will set the first steps towards our effort to automate the release process and migrate the komiser repository to GitHub Actions. In the first step, I added two jobs that, for now, just build and test the `komiser` CLI, as well as the dashboard. The actions will run towards every PR.
Closes #372
> Add GitHub Actions for testing & building komiser

- .github/workflows/build_test_pr.yml
In order to check for style errors, we can leverage [`golangci-lint`](https://golangci-lint.run/) to do this in our CI
> Add golangci-lint to PR action

- handlers/csv_handler.go
- handlers/stats_handler.go
In order to track the feature adoption of export CSV we're collecting its usage frequency (if opt-in by the end-user)
> if opt in collect usage stats (slack & global)

- go.mod
- go.sum
- providers/gcp/storage/storage.go
This PR will add cost estimation for GCP buckets. It's not very trivial to get the bucket size unfortunately, so we use the [GCP Monitoring API](https://cloud.google.com/monitoring/api/v3) to gather metrics about the total bucket size. The cost estimation is done based on `us-central-1` region only for now. 
Note that for this to work, you'll need the `monitoring.timeSeries.list` permission in your service account.
> feat: calculate monthly cost for bucket

- .github/workflows/release.yml
checks wether there were changes in the `helm` repository, before attempting to commit & push
> feat: skip push to helm repo when no changes

- Dockerfile
During `docker build` we used to grab the binary from remote S3, which leaded to the Docker image sometimes not having the latest binary file. This PR changes the Dockerfile to copy the binary from the local /dist folder, which is always up to date after building.
> chore: docker, copy binary from dist

- internal/internal.go
`ListenAndServe` is a blocking function so I had to split to `Listen` and Serve `methods`
> show port number on server start

- dashboard/components/select/Select.tsx
- dashboard/tailwind.config.js
- Adjusted select component inner padding 
- Added new shade of black to tailwind
- [Figma ref](https://www.figma.com/file/eq3JgvmW48IVrYcg2kzgLL/Tailwarden---Design-System?node-id=1624%3A6324&t=Yk9PBv2ct0QHI1Tq-1)
- `npm run storybook`, then choose: `Select`
> style: match select component with figma

- dashboard/components/dashboard/components/cloud-map/DashboardCloudMapError.tsx
- dashboard/package-lock.json
If a given user has loaded the Komiser dashboard, visited the Inventory page, lost internet connection or closed the server, then went back to the dashboard, they will be served either with a default browser error screen (i.e.: there is no internet connection...) or with the Next.js cached HTML/JS version of the page, which shows the dashboard widgets with the error state.
In the case they receive the cached version, the cloud map error state would render like this:
We use an SVG to display the world map as a placeholder, so since there is no connection to load the file, it displays its alt text instead.
Remove the alt property, so in this specific scenario of no internet connection, they would just see a blank space where the map should be.
The error state (not in offline mode) can be …
> fix: cloud map error state offline mode

- dashboard/components/inventory/components/filter/InventoryFilter.tsx
- dashboard/components/inventory/components/filter/InventoryFilterOperator.tsx
- dashboard/components/inventory/components/filter/InventoryFilterSummary.tsx
- dashboard/components/inventory/components/filter/InventoryFilterValue.tsx
- dashboard/components/inventory/hooks/useInventory/helpers/parseURLParams.ts
- handlers/resources_handler.go
- handlers/stats_handler.go
This PR adds two new filters for specific tags, the `does exist/EXISTS` and `does not exist/NOT_EXISTS` filters. The `EXISTS` filter checks if a given tag key is present in a row, respectively `NOT_EXISTS` returns all rows that do not have that key present.
> feat: add EXISTS/NOT_EXISTS query option for specific tags filter

- providers/gcp/gcp.go
- providers/gcp/sql/sql.go
Add Support for SQL Instances in GCP
Closes #674
> Add Support for SQL Instances in GCP

- providers/gcp/gcp.go
- providers/gcp/iam/iam.go
Add Support for IAM Roles (only custom roles will be fetched, the predefined 300 roles aren't displayed) in GCP
Closes #671
> Add Support for Custom IAM roles in GCP

- utils/regions.go
Sao Paulo region was missing in the cloud map widget
> Added Sao Paulo to cloud map

- providers/gcp/gateway/gateways.go
- providers/gcp/gcp.go
Closes #675 
Just like Redis support #709, this also has to query all the zones and does not work with the "global" tag. As of now, both of the methods are called separately hence the same regions call happen twice.
In the near future, a separate feature to just make 1 call and then use that in both the places saving up time as well as compute.
> Add Support for API Gateways in GCP

- providers/aws/iam/policies.go
Closes #729 
Saved up a lot of pre-created default policies (adding 0 to the cloud costs) and their rows from the inventory.
ANDDD
Performance gains by an approx **10x** 🚀 
How:
- Before: Querying atleast 1000 predefined policies from 22 AWS zones 
- After: Querying only user created policies (realistically worst case 100? ) from 22 AWS zones
~~However, we still iterate through the 1000 something extra policies so there definites is a scope for efficiency and performance gains!~~
10x gains lesssgooo!
> Only Parse Used Created Policies from AWS

- providers/aws/aws.go
- providers/aws/ec2/spot_instances.go
> Add Support for AWS EC2 Spot Instance Requests

- cmd/start.go
- internal/internal.go
- main.go
Unfortunately there is some boilerplate required for this to work when it comes to go routines.
> feat: report panics to Sentry

- providers/aws/ec2/elastic_ips.go
Elastic IP run into this nil panic because of an unhandled pointer dereference.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e22669]
goroutine 16 [running]:
github.com/tailwarden/komiser/providers/aws/ec2.ElasticIps({0x3564dd0, 0xc000126048}, {0xc000ff5d40, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
/home/runner/work/komiser/komiser/providers/aws/ec2/elastic_ips.go:67 +0x449
github.com/tailwarden/komiser/providers/aws.FetchResources({_, _}, {0xc000ff5d40, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...}, ...)
/home/runner/work/komiser/komiser/providers/aws/aws.go:96 +0x555
github.com/tailwarden/komiser/internal.fetchResources.func1({0x3564dd0?, 0xc000126048?}, {0xc000ff5d40, 0x0, {0x0, 0x0}, 0x0, 0x0, …
```
> EC2 Elastic IP panic fix

- README.md
Broken links in readme
Add hyphens and encoded-emoji wherever necessary.
Added those characters. Only linking "Roadmap and Contributing" required encoded emoji, others worked just with a hyphen
Click click click
> docs: fix Broken links in README

- providers/aws/aws.go
- providers/aws/rds/db_proxy_endpoints.go
Ability to view RDS Db Proxy endpoint inputs does not exist.
This PR adds a new `db_proxy_endpoints.go` file which queries the AWS Go SDK and implements support for returning RDS ProxyEndpoints.
An entry has also been made to `aws.go` to make sure `rds.ProxyEndpoints` is included
fixes #565
Apply filter in Dashboard:
- Cloud Provider is AWS
- Cloud Service is RDS DB Proxy endpoint
and you should be able to see RDS ProxyEndpoint resources.
WIP
> feat(rds): add RDS db proxy endpoint capabilities

- providers/aws/ec2/keypair.go
Fix for https://github.com/tailwarden/komiser/issues/804
> add account name for AWS ec2 keypair inventories

- Dockerfile
As Usage of MAINTAINER is depricated in Dockerfile
Used
LABEL to define maintainers information
> fix: Dockerfile MAINTAINER label

- providers/aws/cloudwatch/alarms.go
Ability to calculate and view AWS Cloudwatch cost does not exist.
This PR adds a new `cloudwatch.go` file which queries the AWS v2 Go SDK and implements support for calculating AWS cloudwatch alarm costs.
An entry has also been made to `aws.go` to make sure `ec2.CloudWatchAlarms` is included.
fixes #415 
WIP
WIP
@mlabouardy
> feat(aws): estimate aws cloudwatch costs

- dashboard/components/inventory/components/InventoryActiveFilters.tsx
- dashboard/components/inventory/components/InventoryFilterDropdown.tsx
- dashboard/components/inventory/components/filter/InventoryFilter.tsx
- dashboard/components/inventory/components/filter/InventoryFilterSummary.tsx
- dashboard/pages/inventory.tsx
The filter tags on inventory is looking more of a buttons and blending in the background
Changes the style of tags as per figma design
-  Updated the layout and styling of the filter tags.
-  Changed the positioning of the button from absolute to flex to align it within the component.
https://github.com/tailwarden/komiser/assets/29349136/13c30c33-353b-45c1-b84b-f36b568766a4
@mlabouardy
> style(filter-component): redesign filter tag ui

- dashboard/components/dashboard/components/cost-explorer/DashboardCostExplorerCard.tsx
- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorer.tsx
#810 
Changed the granularity payload to reference the state value instead of referencing the function default value.
That way when the select component drop-down changes the correct value is been captured.
No test required
@mlabouardy
> fix: granularity payload bug

- .github/workflows/build_test_pr.yml
- Makefile
Closes #884
Difference in time after the first run is massive thanks to the omnipresent **CACHING**
We start caching test outputs now to prevent repeated runnings when nothing has changed!
This, although, does not optimise the core `make test` command, it leverages the caching ability of github actions' setup-go package to help us
> Optimise CI: Cache Go Builds

- dashboard/components/inventory/components/InventoryActiveFilters.tsx
- dashboard/components/inventory/components/view/InventoryView.tsx
- dashboard/components/inventory/components/view/InventoryViewHeader.tsx
- dashboard/pages/inventory.tsx
The save View button was not aligned with figma design
Have transferred it to The Active filters bar as per Figma design
- moved the view button component from a separate component to the children of the active component so that it will align with the active filters.
- corrected the design and alignment of the button to match the design in Figma.
https://github.com/tailwarden/komiser/assets/29349136/015d83b9-1530-4042-8478-75c4e7951bbd
@mlabouardy @ShubhamPalriwala
> fix(save-button): fixed save button layout

- providers/aws/aws.go
- providers/aws/rds/auto_backups.go
Ability to view RDS Auto Backup Resource does not exist.
This PR adds a new `providers/aws/rds/auto_backups.go` file which queries the AWS Go SDK and implements support for returning RDS AutoBackups.
An entry has also been made to `providers/aws/aws.go` to make sure `rds.AutoBackups` is included
fixes #559 
Apply filter in Dashboard:
- Cloud Provider is AWS
- Cloud Service is RDS Backup
and you should be able to see RDS Backup.
wip
> feat: collect aws rds auto backup resources

- VERSION.md
This documents the Versioning guidelines that we plan to follow for Komiser!
> Versioning Guidelines

- dashboard/components/input/Input.tsx
In **Inventory** section, under the **tags** management, input fields in normal state have border size larger than the design suggested.
Issue #842
After inspecting the code, it was found that the outline-width property of the Input Components used in multiple parts of UI was 2px in normal state. For normal state, it should be 1px.
- Reduced the outline-width of Input Component to 1px in active state.
Screenshot after the fix
@mlabouardy
> Fixing issue#842: input fields under tags management was unreasonably large

- providers/aws/aws.go
- providers/aws/elb/targetgroups.go
Add support for AWS ELB Target Groups using Komiser. Closes #540 
- Added support for getting AWS ELB Target Groups(elb/targetgroups.go)
-  Added `elb.TargetGroups` to `aws.go`
- Make sure your AWS account has Target Groups
- Build and run this branch
- Choose `Target Group` as service filter
> Added support for AWS Load balancer Target Groups

- providers/aws/elb/loadbalancers.go
Solves the issue #914 
Remove the / in the URL 
- Removed a **/** after **#** in the URL
- Build and run the current Develop branch
- Go to Inventory -> All resources -> Filter -> Cloud service -> is -> ELB
- Click one of the Load Balancers and click the link beside the Load Balancer's name
> Removing a / thats breaking the AWS console Load Balancer URL in the UI

- providers/aws/elb/loadbalancers.go
Solves #533 
- Add functionality to get listeners 
- Modified the existing `elb/loadbalancer.go` file with code to get listeners for each loadbalancer
- Make sure your AWS account has ELB Listeners
- Build and run this branch
- Choose `ELB Listener` as the service filter option
> Added support for AWS ELB Listeners

- providers/aws/iam/oidcproviders.go
Solves #918 
Fixed the URL 
- Added URL encoding and updated URL path
1. Build and run the current Develop branch
2. Go to Inventory -> All resources -> Filter -> Cloud service -> is -> IAM Identity Provider
3. Click one of the IAM Identity Provider and click the link beside the IAM Identity Providers name.
User is taken to the Identity Provider page without issues :point_down:
> Fix/918 Updated IAM Identity Provider console URL

- dashboard/components/layout/Layout.tsx
I just found that I was being redirected to the onboarding wizard everytime I was running the dashboard! This limits our current use because the wizard is not entirely functional!
I have disabled it for now using the flag, and let's enable it after getting all the features for it made and thoroughly tested!
> Disable Onboarding Wizard until Ready

- providers/aws/elb/loadbalancers.go
Fixes #539 #538 #537 #536
- Updated code to show the different types of ELB and Listeners based on `loadbalancer.Type`
- Added support to view different types of ELB's and Listeners
1. Make sure your AWS account has AWS Application/Network/Gateway ELB
2. Build and run this branch
3. Choose ELB Application/Network/Gateway as the service filter option
4. Follow step 3 but pick listeners.
Need help testing Network and Gateway loadbalancer options
> Added support for ELB and Listener types

- dashboard/components/onboarding-wizard/PurplinCloud.tsx
- dashboard/components/onboarding-wizard/SelectInput.tsx
- dashboard/components/select/Select.tsx
- dashboard/pages/onboarding/provider/kubernetes.tsx
remove warning in CI: https://github.com/tailwarden/komiser/actions/runs/5984338315/job/16235397277#step:5:38
```./pages/onboarding/provider/kubernetes.tsx
31:4  Warning: Delete `,`  prettier/prettier
57:5  Warning: Unexpected console statement.  no-console
./components/onboarding-wizard/DatabasePurplin.tsx
10:25  Warning: Replace `l-12·-mb-14` with `b-14·-ml-12`  prettier/prettier
./components/onboarding-wizard/PurplinCloud.tsx
15:32  Warning: Replace `top-[53%]·left-[48` with `left-[48%]·top-[53`  prettier/prettier
./components/onboarding-wizard/SelectInput.tsx
[38](https://github.com/tailwarden/komiser/actions/runs/5984338315/job/16235397277#step:5:39):49  Warning: Replace `right-4⏎········bottom-[1.15rem]` with `bottom-[1.15rem]⏎········right-4`  prettier/prettier
52:110  Warning: …
```
> Remove some warning in CI

- docs/mint.json
Removed default api docs from the sidebar
> remove api docs from sidebar

- handlers/accounts_handler.go
- internal/api/v1/endpoints.go
- models/database.go
Through the new onboarding wizard, users would be able to connect Komiser to an external database (Postgres or SQLite), hence an API endpoint is needed to establish the connection.
Exposed a new endpoint to allow users to connect an external database.
The following endpoint can be used to integrate a database:
`POST /databases`
It expects the following payload:
```json
{
"type": "SQLITE",
"file": "komiser.db"
}
{
"type": "POSTGRES",
"hostname": "localhost:5432",
"username": "komiser",
"password": "komiser",
"database": "demo"
}
```
> Expose config database endpoint

- providers/gcp/bigquery/tables.go
Issue #784 
Cost for bigquery table is dependant on the storage class of the table and if table hasn't been modified in 90 days then it's in longterm storage else it's in active storage.
ref: [BigQuery Table pricing](https://cloud.google.com/bigquery/pricing#storage)
- Added function for fetching storage class based pricing
- Added function to determine storage class
- I didn't find any API by GCP for fetching latest prices, hence I've used hardcoded values.
- Assumed billing on logical bytes used, which is default. GCP has option for physical bytes too which has different rates.
- Fixes #784 
> Bigquery table cost calculation

- providers/aws/aws.go
- providers/aws/iam/users.go
Ability to see AWS IAM Users did not exist
This PR adds a new `user.go` file which queries the AWS v2 Go SDK and implements support for calculating AWS IAM Users.
An entry has also been made to `aws.go` to make sure `iam.Users` is included.
fixes #547 
Open Dashboard and apply relevant filters to see iam users
@mlabouardy @jakepage91
> support aws iam user

- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorer.tsx
- dashboard/components/dashboard/components/cost-explorer/hooks/useCostExplorerChart.tsx
- dashboard/components/dashboard/components/cost-explorer/utils/dateHelper.ts
#811  
Fixed the  period  filter for "Last 6 months" to exclude this month and added a new period  filter for "This month" in cost explorer.
- Added a date helper function for getting first day of this month.
- Added the UI option for selecting "This month" period & subsequent changes to support that option.
- Try cost explorer with "This month" period, it'll show data for only this month.
- Try cost explorer with "Last 6 months" period, it won't include this month's data anymore.
- Fixes #811 
- I considered adding date pickers or date range widget but skipped it now for the lack of a design.
@mlabouardy 
@naisayer
> Cost explorer

- providers/k8s/opencost/opencost.go
All Opencost fields are` float64` in their structs and `number` in swagger. Using `int` on our end may cause issues.
ref:-
- https://github.com/opencost/opencost/blob/develop/docs/swagger.json
- https://github.com/opencost/opencost/blob/6a7d9ada3cd0422701c90b5df214b8bf322b0e62/pkg/kubecost/allocation_json.go#L13
Converted all `int` fields to `float64` in opencost costdata struct.
- Added the references as code comments
- Converted all `int` fields to `float64` in the relevant struct.
- Added more fields which might be useful in the future
@mlabouardy 
@AvineshTripathi
> opencost struct types update

- dashboard/components/icons/AlertCircleIconFilled.tsx
- dashboard/components/onboarding-wizard/CredentialsButton.tsx
- dashboard/components/onboarding-wizard/DatabaseErrorMessage.tsx
- dashboard/components/onboarding-wizard/InputFileSelect.tsx
- dashboard/components/onboarding-wizard/LabelledInput.tsx
- dashboard/pages/onboarding/choose-database.tsx
- dashboard/pages/onboarding/database/postgres.tsx
- dashboard/pages/onboarding/database/sqlite.tsx
- dashboard/services/settingsService.ts
Today users have no possibility to add a database
> feat: allow user to configure a database

- dashboard/components/cloud-account/hooks/useCloudAccounts/useCloudAccount.ts
- dashboard/pages/cloud-accounts.tsx
- dashboard/services/settingsService.ts
Today a user can access the Cloud accounts page even if he hasn't added any accounts.
This PR check with the API if the onboarding has been completed (both cloud accounts and database has been setup) and if not it redirects them to the corresponding page.
> Display onboarding wizard if no cloud account was connected

- providers/aws/lambda/functions.go
- providers/aws/utils/utils.go
- providers/aws/utils/utils_test.go
AWS Lambda costs were off by ~1000x magnitude.
The calculation for duration was off, it needed to bed divided by 1024 to get correct units.
- Added common utils for AWS cost calculations
- Fixed AWS Lambda cost calculation
- Took free tier into account
- Pay more attention towards the common utils as, if correctly implemented, these can be used throughout aws provider.
> Aws Lambda cost calculation improvements

- dashboard/components/explorer/DependencyGraph.tsx
- dashboard/components/tooltip/Tooltip.stories.tsx
- dashboard/components/tooltip/Tooltip.tsx
The tooltip is broken in a way that for unknown reasons `classNames` is not overriding classes properly. Taking the following component:
```typescript
function Tooltip({
children,
top = 'md',
align = 'left',
width = 'md'
}: TooltipProps) {
console.log(top, 'top');
return (
<div
role="tooltip"
className={classNames(
'absolute left-6 top-24 z-[1000] hidden animate-fade-in-up items-center rounded-lg bg-black-900 px-4 py-2 text-xs font-medium text-black-200 opacity-0 peer-hover:flex',
{ 'top-0': top === 'xs' },
{ 'top-[3rem]': top === 'sm' },
{ 'left-auto right-0': align === 'right' },
{ 'w-72': width === 'lg' }
)}
>
{children}
</div>
);
}
```
and using it as follows
```typescript
<div className="relative">
<WarningIcon className="peer" height="16" width="16" />
<Tooltip top="xs" align="left" …
```
> fix: fix tooltip component positioning and add it to storybook

- dashboard/components/layout/Layout.tsx
We're always redirecting to `/dashboard` when doing a full reload.
We actually only want to redirect to `/dashboard` when trying to access the completed onboarding wizard. An added path check prevents unnecessary redirects.
- Add check if we're actually trying to access the onboarding wizard and only then redirect based on completion status!
Do a full reload on any page. You should stay on that page instead of getting redirected to `/dashboard`
Not needed
None
Code owners
> fix: prevent redirecting when not visiting the onboarding wizard

- providers/k8s/core/nodes.go
- providers/k8s/k8s.go
Calculating costs for kubernetes nodes was yet to be added. 
Adding support for kubernetes nodes cost calculation.
- Added a new `nodes.go` file to the kubernetes provider.
- Also, found a duplicate in `listOfSupportedServices()` and removed it.
- Fixes #1039 
> feat: support k8s nodes

- CONTRIBUTING.md
With this PR, the existing contributing guide has been revamped with the focus on guiding new contributors on the right path to get involved in the Komiser project!
- more structured
- different ways to contribute (Komiser Engine & UI)
- best practices while contributing
@jakepage91 @AvineshTripathi 
Fixes #1029
> [Feature] Enhancing the Contributing Guide

- docs/configuration/cloud-providers/aws.mdx
This PR is about the following feature:
https://github.com/tailwarden/komiser/issues/548
As far as I can see Kinesis Data Streams are already supported.  
The only missing part was having it documented in the supported resources.
- Only updated the documentation to add KDS to the list of supported resources.
I tested by creating a Kinesis Data Stream in my AWS account.  
Komiser was able to find it and display it.
n/a
@jakepage91
> Adding Kinesis Data Streams to the list of supported resources

- providers/k8s/core/services.go
Currently komiser doesn't provide cost for k8s services. Its always 0. This PR fixes that. Implementation is similar to others, using opencost to generate the cost for services.
- Added GetOpencostInfo for service
> add cost for k8s services

- providers/k8s/core/namespaces.go
- providers/k8s/k8s.go
Calculating costs for kubernetes namespaces was yet to be added.
Adding support for kubernetes namespaces cost calculation.
- Added a new `namespaces.go` file to the kubernetes provider.
- Fixes https://github.com/tailwarden/komiser/issues/1038
> feat: support k8s namespaces

- CONTRIBUTING.md
- docs/configuration/cloud-providers/aws.mdx
- docs/getting-started/quickstart.mdx
I believe there is a slight error in the documentation.  
The path is a string and should use double quotes.  
Otherwise we end up with this error:
Updated the documentation to use double quotes.
- Updated the documentation to use double quotes.
This is a documentation change, so no tests are available.
@mlabouardy
@jakepage91
> doc: path is a string and should use double quotes

- internal/config/load.go
- providers/gcp/compute/instances_test.go
With the two proposals accepted (https://github.com/golang/go/issues/42026 and https://github.com/golang/go/issues/40025), the package io/ioutil has been deprecated
since Go 1.16
This PR removes remaining traces of it.
- Replaced ioutil with either os or io package
komiser start --config config.toml
This is just groundwork for getting the linter in
> chore: drop deprecated ioutil

- .github/workflows/lint.yml
- go.mod
- handlers/feedback_handler.go
- migrations/20230413100000_set_default_tags_in_resources.go
- migrations/20230602100000_create_custom_webhook_fields_in_alerts.go
- migrations/20230619100000_add_new_relation_field.go
- migrations/20231014100000_add_new_status_field.go
- providers/aws/ec2/elastic_ips.go
- providers/aws/elasticache/clusters.go
- providers/gcp/kms/keys.go
- utils/database.go
- utils/gcpcomputepricing/disk.go
- utils/gcpcomputepricing/machine.go
- utils/gcpcomputepricing/snapshot.go
There are no lint checks in place currently. 
This PR adds golangci-lint support. The lint checks are done via github-actions only.
- Added lint.yml for golangci-lint runs
- Fixed some lint errors as well
- to run linter, run `golangci-lint run`
- to star komiser, run `komiser start --config=config.toml`
> Initial Lint Support

- providers/k8s/core/daemonsets.go
- providers/k8s/core/jobs.go
- providers/k8s/core/statefulsets.go
- providers/k8s/k8s.go
Calculating costs for multiple kubernetes controllers were yet to be added.
Adding support for kubernetes controllers cost calculation.
Added support for:
- `statefulsets.go`
- `jobs.go`
- `daemonsets.go`
Fixes https://github.com/tailwarden/komiser/issues/1037
> feat: support k8s controllers

- providers/aws/s3/buckets.go
Currently cost for AWS S3 is always showing as $0.
This PR is fixing that issue by adding more filters and usage metrics for request to s3 bucket with absolute pricemap fetching.
- Fetching price info using AWS SDK price module using `AmazonS3` service code and appropriate filters.
- getting price map using util function GetPriceMap from [utils.go](https://github.com/tailwarden/komiser/blob/develop/providers/aws/utils/utils.go)
- fetching resource objects using S3 client
- also fetching usage metrics as request using cloudwatch
- Finally added calculation as per all the metrics
Taking ref from :- #1053
> feat: Fix cost calculations for AWS S3

- docs/configuration/cloud-providers/aws.mdx
- mocks/kinesis.go
- policy.json
- providers/aws/kinesis/streams.go
- providers/aws/kinesis/streams_test.go
So far EFO consumers were note shown in the inventory.  
It could make sense to show them, because each EFO consumer incurs additional charges.
Use the `ListStreamConsumers` method provide by AWS to least the consumers for each Kinesis Data Stream.
- Modified `streams.go` so that EFO consumers are retrieved.
- Added unit tests with 100% coverage on the new code added.
- Added a mock for Kinesis Client to be used in unit tests
- Updated the IAM policy so that `kinesis:ListStreamConsumers` is allowed
- Updated the list of supported resources in the documentation
In order to test the changes you first need to create a Kinesis Data Stream.  
Then you need to register an EFO consumer, for instance using the AWS cli:
`aws kinesis register-stream-consumer --stream-arn …
> feat: add support of Kinesis EFO Consumers

- CONTRIBUTING.md
- dashboard/README.md
Improve the contribution guidelines with missing informations for frontend development onboarding. Also add links to internal document references and cross-reference the QUickstart Guide for adding a `config.toml`
Instruvtions are missing some key steps which is referecnes externally. This PR add the missing steps and cross-reference external documentation for things like setting up the `config.toml`
- Link references to internal sections
- Fix spelling mistakes
- Add content for missings steps
- Improve the README inside `/dashboard` for frontend specific thigns (TBD)
Read the `.md` files and make sure they parse fine. That's it.
None needed. Use GitHub Markdown preview
> Update Contribution Guidelines

- providers/aws/ec2/instances.go
[Click here to view the issue ticket](https://github.com/tailwarden/komiser/issues/1089)
Runtime Error: Invalid Memory Address or Nil Pointer Dereference during Fresh Install
need nil check for instance key pair name. because we are using ec2 instance with Ec2 session managers. in this case we don't have an ec2 key pair for the instance.
- Added nil Check on KeyPair checking
- create ec2 instance without key pair
- run the komiser and test it
>  #1089 Added nil check on associated KeyPair

- .github/workflows/lint.yml
golangci-lint was had stopped running due to https://github.com/golangci/golangci-lint-action/issues/135
Also, it was running on `push` events instead of `pull_request` events
skipping pkg cache
> fix: golangci lint

- providers/aws/kinesis/streams.go
So far Kinesis Data Streams had no tags, which made them being displayed is the untagged resources section. 
Call the function `ListTagsForStream()` to retrieve the list of tags for each stream.
- Updated the `streams.go` file to retrieve the tags
Create a Kinesis Data Stream and assign some tags to it.
Next I will probably tackle the cost calculations for Kinesis.
@mlabouardy
@AvineshTripathi
> feat: retrieve tags of Kinesis Data Streams

- dashboard/README.md
- dashboard/tsconfig.json
- dashboard/utils/formatNumber.test.ts
- dashboard/utils/regex.test.ts
Readme was slightly outdated and infos where missing
Provided more test examples, updated reuirements and re-formatted the content.
- Reformat Readme
- Add more details about folder aliases
- Add more details about testing
- Add one more testing example
- Update utils test names
-
-
-
> Improve dashboard readme

- dashboard/environments/environment.ts
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/pages/_app.tsx
Integrate Formbricks In-App Surveys
> feat: integrate formbricks in-app survey

- providers/scaleway/compute/instances.go
https://discord.com/channels/932683789384183808/1163851488288845884/1164167155835732088
```
INFO[2023-10-18T11:44:36+02:00] Debug logging is enabled
INFO[2023-10-18T11:44:36+02:00] Data will be stored in SQLite
INFO[2023-10-18T11:44:36+02:00] there are no new migrations to run (database is up to date)
INFO[2023-10-18T11:44:36+02:00] Komiser version: 3.0.20, commit: 5c3fe4df9497a48d9bae017193e3c73c320ade31, buildt: 1688681410
INFO[2023-10-18T11:44:36+02:00] Fetching resources workflow has started
WARN[2023-10-18T11:44:36+02:00] Newer Komiser version is available: v3.1.1
WARN[2023-10-18T11:44:36+02:00] Upgrade instructions: https://github.com/tailwarden/komiser
INFO[2023-10-18T11:44:36+02:00] Fetched resources                             account=pmw-scaleway-account provider=Scaleway …
```
> fix: nil pointer scaleway

- dashboard/components/explorer/filter/DependendencyGraphFilter.tsx
- dashboard/components/feedback-widget/FeedbackWidget.tsx
- dashboard/components/upload/Upload.stories.tsx
- dashboard/components/upload/Upload.tsx
Update unmerged`useToast` imports
@Traxmaxx
> fix: update toast imports

- dashboard/components/explorer/DependencyGraph.tsx
- dashboard/components/feedback-widget/FeedbackWidget.tsx
- dashboard/components/upload/Upload.stories.tsx
In the current implementation of the Cytoscape graph, we have two issues. First, when users zoom out while hovering over a node relation, the tooltip persists on the screen even after moving the mouse. This behavior can stack and lead to multiple tooltips staying on the screen. Second, when users hover over the tooltip, they are unable to zoom out.
fixes #1066 
To solve these issues, I’ve added checks in the zoom event handler to remove any tooltips when zooming crosses its threshold i.e. zoomLevelBreakpoint. I’ve also disabled pointer events on the tooltip to allow zoom events to pass through.
- Added a check in the zoom event handler to remove tooltips when zooming crosses breakpoint.
- Disabled pointer events on tooltips to allow zoom events to pass through.
- Commented the extra …
> fix: relation name persisting on screen while hovering graph edges #1066

- dashboard/components/explorer/config.ts
- dashboard/styles/globals.css
Labels were broken
Fixed them
- Update CSS classes to new `dependency-graph-nodeLabel` class instead of `dependency-graph-node-label`
Before:
After the fix:
> fix: fix labels on resource explorer

- providers/civo/civo.go
- providers/civo/storage/databases.go
Civo Databases were not being detected
The size was not being sent in GB but as the instance name. Wrote & used a utility function to map all available instance types to their respective sizes in GB.
@jakepage91 @mlabouardy @AvineshTripathi
> fix: Civo Database not detected

- providers/digitalocean/storage/volumes.go
Currently, cost calculation for DigitalOcean volumes is not implemented!
This PR is fixing tiny issue by adding cost calculation support for volumes of digitalocean
- Fetching the sizein GB of volume and then calculating the cost based on the fixed price from digitalocean volume [pricing](https://www.digitalocean.com/pricing/volumes)
- fixed the hourly cost as static since its same for all volumes
> feat: Add Cost Calculation for DigitalOcean Volumes

- internal/internal.go
- providers/mongodbatlas/mongodbatlas.go
Synchronous fetching of resources for MongoDB
Submitting the tasks to worker pool instead of executing synchronously.
-Update respective function signature
-Use `providers.WorkerPool.SubmitTask` to submit the task to worker pool
> fix(1206): Resource fetching performance improvement for MongoDb

- internal/internal.go
- providers/scaleway/scaleway.go
Synchronous fetching of resources for Scaleway
Submitting the tasks to worker pool instead of executing synchronously.
- Updated respective function signatures
- Used `providers.WorkerPool.SubmitTask` to submit the task to worker pool
> fix: Resource fetching performance improvement for Scaleway

- providers/aws/ec2/instances.go
Fixes #1250
A couple of nil pointer dereference errors appeared for me while enumerating resources across multiple AWS accounts.
Include a simple check that `inst.VpcId` and `inst.SubnetId` are not nil prior to adding them as a link.
- check that `inst.VpcId` is not nil prior to using it in a `models.Link`
- check that `inst.SubnetId` is not nil prior to using it in a `models.Link`
This error appeared very shortly after running `komiser start`. As described in #1250, I have two AWS accounts configured. This may or may not be an important piece of information for this bug.
I do not know why the EC2 instance resource came back with nil values for VPC ID and Subnet ID. This behavior only occurred _after_ I had deleted a few EC2 instances from one AWS account. However, when I removed the …
> Check for nil VpcId and SubnetId before use

- docs/configuration/cloud-providers/aws.mdx
Curly brackets are currently not directly supported. They can either be supported with backticks or `\`
Added backticks 
Run `mintlify dev` and navigate to http:localhost:3000/configuration/cloud-providers/aws)
> Escape Curly Brackets

- policy.json
Actions missing from the recommended [komiser policy](https://raw.githubusercontent.com/mlabouardy/komiser/master/policy.json)
Add required actions to the policy (using https://aws.permissions.cloud/ as IAM <> API reference)
- Updated policy.json
Run komiser with the recommended policy and an AWS environment with affected resource.
> fix: add missing actions to policy.json

- .github/dependabot.yml
Configure dependabot for Go dependency to manage go dependencies version.
> Configure dependabot for Go dependency

- dashboard/components/account-details/KubernetesAccountDetails.tsx
- handlers/accounts_handler.go
- handlers/helper.go
- Onboarding wizard doesn't schedule the fetching of resources
- No support for opencost in onboarding wizard
- Used gocron to fetch resources for added account every hour
- New input field in kubernetes part of onboarding wizard
@jakepage91 @mlabouardy @AllieMendes
> Onboarding wizard enhancements

- handlers/dashboard_handler.go
- providers/aws/aws.go
- providers/aws/utils/utils.go
Komiser only records cost data from the instant it's started, ignoring past data
Use AWS cost explorer API to fetch and store 6 months cost history
> feat: 6 month cost data history

- handlers/accounts_handler.go
Fetching resources workflow getting scheduled but not running immedeately
calling `cron.StartAsync` to start the job(s) without blocking current thread
> fix: fetching for wizard getting scheduled, not running immedeately

- handlers/csv_handler.go
Added Service Name and Metadata as I wanted them when downloading CSV from Inventory on Komiser.
I know you can sort by Service Name, etc. on Komiser, but I would like to do this on CSV as well.
I also added Metadata because I want to see what is associated with a resource such as an Instance (e.g. EBS).
get datas and headers are added to the CSV generation points(`handlers/csv_handler.go`) in the backend.
- Get metadata and service name from data fetching from database.
I downloaded csv from komiser frontend.
Downloaded csv's screenshot. (Account ID, etc. are rewritten manually.)
> feat: service and metadata fields add to CSV export

- controller/controller.go
- handlers/resources_handler.go
- repository/postgres/postgres.go
- repository/sqlite/sqlite.go
Repository and Controller were not initialized
Initialized a repository and attached it to APIHandler
> fix: uninitialized controller and repo

- providers/tencent/cvm/instances.go
I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.
see issues https://github.com/alingse/go-linter-runner/issues/1
and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9242674625/job/25425792291 
```
====================================================================================================
append to slice `tags` with non-zero initialized length at https://github.com/tailwarden/komiser/blob/develop/providers/tencent/cvm/instances.go#L48:11
====================================================================================================
```
- [List the …
> fix: fix miss makezero bug

- dashboard/utils/serviceHelper.ts
- go.mod
- go.sum
- providers/azure/azure.go
- providers/azure/networking/local_network_gateways.go
- providers/azure/resourcegroup/resource_groups.go
Solving Issue #396 
Adding resource
added local network gateway
also created a function to get the resource groups in the subscription to be able to call all the local network gateways, as function do not call under a subscription level
Added a new local network gateway in the Azure subscription, test if it shows successfully in Komiser. Cost is not showing, as LNGs do not generate cost.
@jakepage91
> create local network gateway resource
